---
title: "plot_visualisation"
format: html
---

# 2a. Ver채nderung Habitatverf체gbarkeit in Abh채ngigkeit versch. Abfl체sse 
```{r}
library("readr")
library("tidyr")
library("dplyr")
library("ggplot2")
# install.packages("ggforce")
library("ggforce")
library(gridExtra)
# make data frame for plotting -------------------------------------------
WUA_HHS <- read_delim("results_statistics/Results_Multivariate_Habitat_Model.csv")

WUA_VZH <- read_delim("results_statistics/Results_VZH_Habitat_Model.csv")

# Rename a column using colnames()
colnames(WUA_HHS)[colnames(WUA_HHS) == "WUA_pers_GHSI"] <- "WUA_pers"

results |> 
  pivot_longer(cols = c(HHS, HHS_pers)) |> 
  ggplot(aes(Discharge, value, col = Description)) +
  geom_point()+
  geom_line()+
  facet_wrap(~name)

# bind the two data frames together --------------------------------------
results <- bind(WUA_HHS, WUA_VZH)

# HHS normal 
plot1 <- ggplot(results, aes(Discharge, HHS, col = Description)) +
  geom_point(size = 2) +
  geom_line(lwd = 0.7) +
  labs(title = "Hydraulic Habitat Suitability (HHS)", subtitle = "Comparing three Macroinvertebrates and FOEN",  x = expression(paste("Discharge [", m^3/s, "]")), y = "HHS [-]", col = "Macroinvertebrates") +
  theme_gray()

# HHS persistent 
plot2 <- ggplot(results, aes(Discharge, HHS_pers, col = Description)) +
  geom_point(size = 2) +
  geom_line(lwd = 0.7) +
  labs(title = "Hydraulic Habitat Suitability (HHS) of Persistent Habitats", subtitle = "Comparing three Macroinvertebrates and FOEN", x = expression(paste("Discharge [", m^3/s, "]")), y = "HHS [-]", col = "Macroinvertebrates") +
  theme_gray()

# Combine the plots into a single screen
combined_plot_HHS <- grid.arrange(plot1, plot2, ncol = 2)

# WUA normal 
plot3 <- ggplot(results, aes(Discharge, WUA_normal, col = Description)) +
  geom_point(size = 2) +
  geom_line(lwd = 0.7) +
  labs(title = "Weighted Usable Area (WUA)", subtitle = "Comparing three Macroinvertebrates and FOEN", col = "Macroinvertebrates") +
  theme_gray()

# WUA persistent 
plot4 <- ggplot(results, aes(Discharge, WUA_pers, col = Description)) +
  geom_point(size = 2) +
  geom_line(lwd = 0.7) +
  labs(title = "Weighted Usable Area (WUA) of Persistent Habitats", subtitle = "Comparing three Macroinvertebrates and FOEN", col = "Macroinvertebrates") +
  theme_gray()

# Combine the plots into a single screen
combined_plot_WUA <- grid.arrange(plot3, plot4, ncol = 2)
```


```{r}
# WA tot results -----------------------------------
WA_tot_results <- ggplot(WUA_HHS, aes(Discharge, WA_tot)) +
  geom_line(lwd = 0.7) +
  geom_point(size = 2) +
  labs(title = "Comparing total wetted area of 13 discharges", x = expression(paste("Discharge [", m^3/s, "]")), y = expression(paste("Wettet Area [", m^2, "]"))) +
  theme_gray()
```

```{r}
# save plots into .png
# set the dimensions of the quadrat
quadrat_width <- 30 # in cm
quadrat_height <- 25 # in cm

# HHS 
ggsave(filename = "results_statistics/HHS_results.png",plot = combined_plot_HHS, width = quadrat_width, height = quadrat_height, units = "cm")

quadrat_width1 <- 30 # in cm
quadrat_height1 <- 15 # in cm

# WUA
ggsave(filename = "results_statistics/WUA_results.png",plot = combined_plot_WUA, width = quadrat_width, height = quadrat_height, units = "cm")

# WA_tot
ggsave(filename = "results_statistics/WA_tot_results.png",plot = WA_tot_results, width = quadrat_width, height = quadrat_height, units = "cm")
```

## f. calculate areas - make barplot 
```{r}
# All scenarios ------------------------------------------------------
# Rhithrogena sp. -----------------------------------
freq_GHSI_Tanno_2012_Rhithrogena_2 <- freq_table(GHSI_Tanno_2012_Rhithrogena_2)

freq_GHSI_Tanno_2012_Rhithrogena_9 <- freq_table(GHSI_Tanno_2012_Rhithrogena_9)

freq_GHSI_Tanno_2012_Rhithrogena_pers_9 <- freq_table(persistent_tanno_2012_rhithrogena_9)

# Rhithrogena HABBY ----------------------------------
freq_GHSI_HABBY_Rhithrogena_2 <- freq_table(GHSI_HABBY_Rhithrogena_2)

freq_GHSI_HABBY_Rhithrogena_9 <- freq_table(GHSI_HABBY_Rhithrogena_9)

freq_GHSI_HABBY_Rhithrogena_pers_9 <- freq_table(persistent_habby_rhithrogena_9)

# Baetis sp. ---------------------------------------------------
freq_GHSI_Tanno_2012_Baetis_2 <- freq_table(GHSI_Tanno_2012_Baetis_2)

freq_GHSI_Tanno_2012_Baetis_9 <- freq_table(GHSI_Tanno_2012_Baetis_9)

freq_GHSI_Tanno_2012_Baetis_pers_9 <- freq_table(persistent_tanno_2012_baetis_9)
```


```{r}
# install.packages("scales")
library(scales)
# load data fresh 
join_multi <- read_delim("results_statistics/multivariate_share.csv")

# Create a new colum as a separate dataframe
join_multi$threshold <- ifelse(join_multi$value =< 0.5, "< 0.5", "> 0.5")

# make long table for plotting
join_long <- pivot_longer(join_multi, cols = c(2:10), names_to = "attribute", values_to = "area")

join_long$value <- as.factor(join_long$value)

# Sort the factor levels in ascending order
colors <- c("0" = "red", "0.1" = "darkorange3", "0.2" = "orange", "0.3" = "sandybrown", "0.4" = "wheat", "0.5" = "lightyellow", "0.6" = "darkolivegreen1", "0.7" = "darkolivegreen3", "0.8" = "darkslategray3", "0.9" = "dodgerblue3", "1" = "blue")

colors2 <- c("=< 0.5" = "red", "> 0.5" = "blue")

# share rhithrogena tanno with all suitabilities 
share_rhith_tanno <- join_long |>
  subset(attribute == c("Rhith_Tanno_2", "Rhith_Tanno_9", "Rhith_Tanno_pers")) |>
  ggplot(aes(attribute, area, fill = value)) +
  geom_bar(stat = "identity", position = "fill")  +
  labs(x = "", y = "") +
  ggtitle("Comparing the Share of Habitat Suitability between Scenarios for Rhithrogena sp.") +
  labs(fill = "Habitat Suitability") +
  scale_x_discrete(labels = c("residual", "hydropeak", "persistent")) +
  scale_y_continuous(labels = function(x) x * 100) +
  scale_y_continuous(labels = percent_format()) +
  scale_fill_manual(values = colors) +
  theme_minimal()

# share rhithrogena tanno with threshold
thresh_rhith_tanno <-join_long |>
  subset(attribute == c("Rhith_Tanno_2", "Rhith_Tanno_9", "Rhith_Tanno_pers")) |>
  ggplot(aes(attribute, area, fill = threshold)) +
  geom_bar(stat = "identity", position = "fill")  +
  labs(x = "", y = "") +
  ggtitle("Comparing the Share of Suitability </> 0.5 between Scenarios for *Rhithrogena sp.*") +
  labs(fill = "Habitat Suitability") +
  scale_x_discrete(labels = c("residual", "hydropeak", "persistent")) +
  scale_y_continuous(labels = function(x) x * 100) +
  scale_y_continuous(labels = percent_format()) +
  scale_fill_manual(values = colors2)
  
# share rhithrogena habby with all suitabilities
share_rhith_habby <-join_long |>
  subset(attribute == c("Rhith_habby_2", "Rhith_habby_9", "Rhith_habby_pers")) |>
  ggplot(aes(attribute, area, fill = value)) +
  geom_bar(stat = "identity", position = "fill")  +
  labs(x = "", y = "") +
  ggtitle("Comparing the Share of Habitat Suitability between Scenarios for Rhithrogena Eaton (larva)") +
  labs(fill = "Habitat Suitability") +
  scale_x_discrete(labels = c("residual", "hydropeak", "persistent")) +
  scale_y_continuous(labels = function(x) x * 100) +
  scale_y_continuous(labels = percent_format()) +
  scale_fill_manual(values = colors) 

# share rhithrogena habby with thresholt
thresh_rhith_habby <-join_long |>
  subset(attribute == c("Rhith_habby_2", "Rhith_habby_9", "Rhith_habby_pers")) |>
  ggplot(aes(attribute, area, fill = threshold)) +
  geom_bar(stat = "identity", position = "fill")  +
  labs(x = "", y = "") +
  ggtitle("Comparing the Share of Suitability </> 0.5 between Scenarios for Rhithrogena Eaton (larva)") +
  labs(fill = "Habitat Suitability") +
  scale_x_discrete(labels = c("residual", "hydropeak", "persistent")) +
  scale_y_continuous(labels = function(x) x * 100) +
  scale_y_continuous(labels = percent_format()) +
  scale_fill_manual(values = colors2) 

# share baetis tanno with all suitabilities
share_baetis_tanno <-join_long |>
  subset(attribute == c("Baetis_2", "Baetis_9", "Baetis_pers")) |>
  ggplot(aes(attribute, area, fill = value)) +
  geom_bar(stat = "identity", position = "fill")  +
 labs(x = "", y = "") +
  ggtitle("Comparing the Share of Habitat Suitability between Scenarios for Baetis sp.") +
  labs(fill = "Habitat Suitability") +
  scale_x_discrete(labels = c("residual", "hydropeak", "persistent")) +
  scale_y_continuous(labels = function(x) x * 100) +
  scale_y_continuous(labels = percent_format()) +
  scale_fill_manual(values = colors) 

# share baetis tanno with threshold
thresh_baetis_tanno <-join_long |>
  subset(attribute == c("Baetis_2", "Baetis_9", "Baetis_pers")) |>
  ggplot(aes(attribute, area, fill = threshold)) +
  geom_bar(stat = "identity", position = "fill")  +
 labs(x = "", y = "") +
  ggtitle("Comparing the Share of Suitability </> 0.5 between Scenarios for Baetis sp.") +
  labs(fill = "Habitat Suitability") +
  scale_x_discrete(labels = c("residual", "hydropeak", "persistent")) +
  scale_y_continuous(labels = function(x) x * 100) +
  scale_y_continuous(labels = percent_format()) +
  scale_fill_manual(values = colors2) 

# save plots into .png
# set the dimensions of the quadrat
quadrat_width <- 15 # in cm
quadrat_height <- 15 # in cm

ggsave(filename = "results_statistics/share_rhith_tanno.png",plot = share_rhith_tanno, width = quadrat_width, height = quadrat_height, units = "cm")

ggsave(filename = "results_statistics/thresh_rhith_tanno.png",plot = thresh_rhith_tanno, width = quadrat_width, height = quadrat_height, units = "cm")

ggsave(filename = "results_statistics/share_rhith_habby.png",plot = share_rhith_habby, width = quadrat_width, height = quadrat_height, units = "cm")

ggsave(filename = "results_statistics/thresh_rhith_habby.png",plot = thresh_rhith_habby, width = quadrat_width, height = quadrat_height, units = "cm")

ggsave(filename = "results_statistics/share_baetis_tanno.png",plot = share_baetis_tanno, width = quadrat_width, height = quadrat_height, units = "cm")

ggsave(filename = "results_statistics/thresh_baetis_tanno.png",plot = thresh_baetis_tanno, width = quadrat_width, height = quadrat_height, units = "cm")
```

## VZH calculate areas - make barplot 
```{r}
# read created dataframe
join_VZH <- read_delim("results_statistics/VZH.csv")

# Create a new row as a separate dataframe
new_row <- data.frame(value = "-",
                      VZH_2 = NA,
                      VZH_9 = NA, 
                      VZH_pers_9 = NA)

# Add the new row to the existing dataframe
join_VZH <- rbind(join_VZH, new_row)

# add correspondent classes to dataframe for plotting
join_VZH$classes <- c("v40 < 5cm/s", "150 < v40 < 250cm/s", "5 < v40 < 25cm/s", "75 < v40 < 150cm/s", "25 < v40 < 75cm/s", "v40 > 250cm/s")

# make long table for plotting
join_long <- pivot_longer(join_VZH, cols = c(2:4), names_to = "attribute", values_to = "area")

# Sort the factor levels in ascending order for plot
join_long$classes <- factor(join_long$classes, levels = c("v40 < 5cm/s", "5 < v40 < 25cm/s", "25 < v40 < 75cm/s", "75 < v40 < 150cm/s", "150 < v40 < 250cm/s", "v40 > 250cm/s"))

# generate colors for barplot 
colors <- c("v40 < 5cm/s" = "yellow", "5 < v40 < 25cm/s" = "green", "25 < v40 < 75cm/s" = "cyan", "75 < v40 < 150cm/s" = "blue", "150 < v40 < 250cm/s" = "magenta", "v40 > 250cm/s" = "red")

# Create plot with share of flow velocity classes per section 
share_VZH <- ggplot(join_long, aes(attribute, area, fill = classes)) +
  geom_bar(stat = "identity", position = "fill")  +
  labs(x = "", y = "Share") +
  labs(fill = "Flow velocity classes", title = "Comparing the Share of Flow Velocity Classes", subtitle = "Between Residual, Hydropeaking and Persistent Habitat Scenarios") +
  scale_x_discrete(labels = c("residual", "hydropeak", "persistent")) +
  scale_y_continuous(labels = percent_format()) +
  scale_fill_manual(values = colors) +
  theme_minimal()
  

# save plots into .png
# set the dimensions of the quadrat
quadrat_width <- 15 # in cm
quadrat_height <- 15 # in cm

ggsave(filename = "results_statistics/share_VZH.png",plot = share_VZH, width = quadrat_width, height = quadrat_height, units = "cm")
```



